### ISSUE TITLE
Title and subtitle

### ISSUE THREAD

**Issue by PeterMathijssen** [Makeroid/docs#7]
What is the use of adding titles and subtitles to pages? I have already made the entire pages of a couple of pages where TurboProgramming only added the Title and subtitle. That is not productive.

**Comment by ardacebi** [comment]
I'm just preparing those pages to make the work easier. I'm going to try to complete those. Of course, I'm not only adding Titles and subtitles. 

I'm opening Pull Requests and editing the documentation because blank pages are not looking good for users, if no content, at least there could be a title and subtitle that explains the component. 

I'm still working on them.

**Comment by barreeeiroo** [comment]
@TurboProgramming Okey, tell us when it's finished 👍

**Comment by ardacebi** [comment]
@barreeeiroo I've opened a new Pull request that completes all Titles and subtitles. Please merge that with makeroid:master so I can fork it again and start writing the rest.
